[workspace]

members = [
  # lib
  "ch01",
  "ch02_loop",
  "ch03_guess_game",
  "ch05_collection",
  "ch07_oo",
  "ch08_closure",
  # "ch10_bench",
  "hello-world",
  "libhello",
  "advance01_serde",
]
