[package]
name = "ch07_oo"
version = "0.1.0"
authors = ["sunquana <sunquana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
